version: '3.8'

services:
  mongodb:
    image: mongo:6-jammy
    ports:
      - '5000:27017'
    volumes:
      - dbdata6:/data/db

  nginx:
    depends_on:
      - api
      - client
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3050:80"

  api:
    build:
      dockerfile: Dockerfile
      context: "./server"
    depends_on:
      - mongodb
    volumes:
      - /app/node_modules
      - ./server:/app
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/leetcode_tracker
    ports:
      - "4000:4000"

  client:
    stdin_open: true
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      dockerfile: Dockerfile
      context: ./client
    volumes:
      - /app/node_modules
      - ./client:/app
    ports:
      - "3000:3000"

volumes:
  dbdata6: